### ISSUE TITLE
Error loading torchio extension

### ISSUE THREAD

**Issue by Reasat** [fepegar/SlicerTorchIO#10]
**🐛Bug**
Error loading torchio extension 

**To reproduce**

I installed slicer and installed torchio extension from the extension manager

**Expected behavior**

Torchio extension loads on starting slicer

**Actual behavior**

Torchio extension does not load on starting slicer

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/reasat/Slicer-4.11.20210226-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/reasat/Slicer-4.11.20210226-linux-amd64/NA-MIC/Extensions-29738/TorchIO/lib/Slicer-4.11/qt-scripted-modules/TorchIOModule.py", line 15, in <module>
    import PyTorchUtils
ModuleNotFoundError: No module named 'PyTorchUtils'
loadSourceAsModule - Failed to load file "/home/reasat/Slicer-4.11.20210226-linux-amd64/NA-MIC/Extensions-29738/TorchIO/lib/Slicer-4.11/qt-scripted-modules/TorchIOModule.py"  as module "TorchIOModule" !
Fail to instantiate module  "TorchIOModule"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/reasat/Slicer-4.11.20210226-linux-amd64/lib/Python/lib/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/reasat/Slicer-4.11.20210226-linux-amd64/NA-MIC/Extensions-29738/TorchIO/lib/Slicer-4.11/qt-scripted-modules/TorchIOTransforms.py", line 19, in <module>
    from TorchIOModule import TorchIOModuleLogic
ImportError: cannot import name 'TorchIOModuleLogic'
loadSourceAsModule - Failed to load file "/home/reasat/Slicer-4.11.20210226-linux-amd64/NA-MIC/Extensions-29738/TorchIO/lib/Slicer-4.11/qt-scripted-modules/TorchIOTransforms.py"  as module "TorchIOTransforms" !
Fail to instantiate module  "TorchIOTransforms"
The following modules failed to be instantiated:
   TorchIOModule
   TorchIOTransforms
Switch to module:  "Welcome"
```

**Slicer version**
4.11.20210226 r29738 / 7a593c8

**Comment by fepegar** [comment]
Hi, @Reasat. Could you please try with a Preview version of 3D Slicer? I.e., the one that is built every night.

**Comment by fepegar** [comment]
I'm going to close this issue as I'm fairly sure that it will work with the Preview Release. Feel free to reopen if it is not the case.

**Comment by Reasat** [comment]
Thanks, that solved it
