### ISSUE TITLE
Paths in README

### ISSUE THREAD

**Issue by dmus** [fepegar/SlicerTorchIO#4]
I noticed the paths in the README are not up to date anymore

I had to change it to:

from pathlib import Path

modulePath = Path('~/git/SlicerTorchIO/TorchIOTransforms/TorchIOTransforms.py').expanduser()
moduleFactory = slicer.app.moduleManager().factoryManager()
moduleFactory.registerModule(qt.QFileInfo(str(modulePath)))
moduleFactory.loadModules([modulePath.stem])

Also I could not run this in using Slicer 4.10.2 because that version uses Python2. I downloaded Slicer 4.13.0, which uses Python3, but I get the following error:

```
Requirement already satisfied: six in ./lib/Python/lib/python3.6/site-packages (from packaging>=14.3->nibabel->torchio) (1.15.0)
TorchIO was installed successfully
Traceback (most recent call last):
  File "/home/derk/SlicerTorchIO/TorchIOTransforms/TorchIOTransforms.py", line 266, in checkTorchIO
    import torchio
  File "/home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/torchio/__init__.py", line 11, in <module>
    from .transforms import *  # noqa: F401, F403
  File "/home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/torchio/transforms/__init__.py", line 1, in <module>
    from .transform import Transform
  File "/home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/torchio/transforms/transform.py", line 13, in <module>
    from ..data.subject import Subject
  File "/home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/torchio/data/__init__.py", line 1, in <module>
    from .queue import Queue
  File "/home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/torchio/data/queue.py", line 9, in <module>
    from .subject import Subject
  File "/home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/torchio/data/subject.py", line 5, in <module>
    from .image import Image
  File "/home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/torchio/data/image.py", line 8, in <module>
    from PIL import Image as ImagePIL
  File "/home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: /home/derk/Downloads/Slicer-4.13.0-2020-11-25-linux-amd64/lib/Python/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

Any ideas? Or should I use a different Slicer version?

**Comment by fepegar** [comment]
Hi, @dmus. You're right about the paths, good catch! I'll change that in a sec.

---

About the second issue. Recent Slicer versions are not very stable. There are issues with VTK and there's also that problem with PIL. I got in touch with Slicer developers about this and they came up with a hack that can be used until this is properly solved: https://discourse.slicer.org/t/slicer-4-11-20200930-cant-import-pip-installed-pillow-on-linux/14448/5
