### ISSUE TITLE
Type error when converting to torch Tensor

### ISSUE THREAD

**Issue by clarkbab** [fepegar/SlicerTorchIO#6]
Hi there, I'm running into an issue when applying any transform through your extension. I have posted version info and python console output below. Thanks

3DSlicer version: 4.11.20200930 r29402 / 002be18
Python version: 3.6.7

Slicer python output:

Transform kwargs:
{'num_control_points': (7, 7, 7), 'max_displacement': (7.5, 7.5, 7.5), 'locked_borders': 2, 'image_interpolation': 'linear'}
Transform args: {'scales': (0.8, 1.2000000000000002), 'degrees': (-10.0, 10.0), 'translation': (0.0, 0.0), 'isotropic': False, 'image_interpolation': 'linear', 'default_pad_value': 'minimum'}
TorchIO returned the error: Traceback (most recent call last):
  File "C:/Users/BACLARK/AppData/Roaming/NA-MIC/Extensions-29402/TorchIO/lib/Slicer-4.11/qt-scripted-modules/TorchIOTransforms.py", line 201, in onApplyButton
    outputImage = self.currentTransform(inputVolumeNode, outputVolumeNode)
  File "C:\Users\BACLARK\AppData\Roaming\NA-MIC\Extensions-29402\TorchIO\lib\Slicer-4.11\qt-scripted-modules\TorchIOTransformsLib\Transform.py", line 118, in __call__
    data, affine = torchio.io.sitk_to_nib(image)
  File "C:\Users\BACLARK\AppData\Local\NA-MIC\Slicer 4.11.20200930\lib\Python\Lib\site-packages\torchio\data\io.py", line 285, in sitk_to_nib
    data = ensure_4d(data, num_spatial_dims=input_spatial_dims)
  File "C:\Users\BACLARK\AppData\Local\NA-MIC\Slicer 4.11.20200930\lib\Python\Lib\site-packages\torchio\data\io.py", line 313, in ensure_4d
    tensor = torch.as_tensor(tensor)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by fepegar** [comment]
Hi, @clarkbab. Thanks for reporting. It looks like you are using a version of Slicer from September, and this is issue was fixed in December (https://github.com/fepegar/torchio/pull/380). Could you please download a more recent version of Slicer and try again?

**Comment by fepegar** [comment]
Were you able to solve this?
